### PR TITLE
checks in sample data and updates readme with correct path

### PR DESCRIPTION
**Pull request by ablwr**
Hello. My first PR! Let me know what the review process is like and if I am doing it right. 😎

### CODE REVIEW

**Review by kfriedman — APPROVED** [review]
🎉  Yay! Nice work. Thanks for jumping in on this!

**Comment by ablwr** [comment]
VERY quick approval. Are you sure it's production-ready??? 😆 😆 😆

**Comment by ablwr** [comment]
Is the local policy that the merge is on the PR-opener, or the reviewer?

**Comment by ablwr** [comment]
Kevin answered me offline.

**Pull request merged**
